### ISSUE TITLE
SyntaxError in Demo

### ISSUE THREAD

**Issue by liuzongying** [thunlp/THULAC-Python#57]
import thulac

thu1 = thulac.thulac(seg_only=True, model_path='C:\Users\liu zongying\Documents\Python\Zongying\THULAC-Python-master\thulac')  #设置模式为行分词模式
a = thu1.cut("我爱北京天安门")

print(a)

I used python3.7 to run demo, and defined the path of model, but error is shown as follow:
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by gzp9595** [comment]
Hi, you run the THULAC in windows system, I think.

This bug is caused by a path input error. You need write path like “C:\\Users\\liu zongying\\Documents\\Python\\Zongying\\THULAC-Python-master\\thulac”

Thank you!


发送自 Windows 10 版邮件应用

发件人: liuzongying
发送时间: 2017年12月19日 16:37
收件人: thunlp/THULAC-Python
抄送: Subscribed
主题: [thunlp/THULAC-Python] SyntaxError in Demo (#57)

import thulac
thu1 = thulac.thulac(seg_only=True, model_path='C:\Users\liu zongying\Documents\Python\Zongying\THULAC-Python-master\thulac') #设置模式为行分词模式
a = thu1.cut("我爱北京天安门")
print(a)
I used python3.7 to run demo, and defined the path of model, but error is shown as follow:
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by liuzongying** [comment]
Thank you, problem is solved
